apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1 
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: localhost:8081/apache/gittest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred



        
