apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment1
  namespace: test
spec:
  selector:
    matchLabels:
      app: httpd1
  replicas: 1 
  template:
    metadata:
      labels:
        app: httpd1
    spec:
      containers:
      - name: httpd1
        image: 192.168.182.138:8081/test/httpd1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: jfrog
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service1
  namespace: test
spec:
  selector:
    app: httpd1
  ports:
    - name: httpd1
      port: 80
      nodePort: 30052
  type: NodePort
