# Stage 1
FROM node:14-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN ./node_modules/@angular/cli/bin/ng build --configuration=production

# Stage 2
FROM nginx:1.17.1-alpine
COPY ops/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-step /app/dist/singlesignon /usr/share/nginx/html
