apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: 192.168.182.165:8081/test/single
        ports:
        - containerPort: 80
        resources:
          limits: 
            cpu: 500m
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: jfrog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auto-httpd-deployment
  namespace: test
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpd-deployment
  targetCPUUtilizationPercentage: 10
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: test
spec:
  selector:
    app: httpd
  ports:
    - name: httpd
      port: 80
      nodePort: 30051
  type: NodePort


        
