apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-vol
      volumes:
      - name: test-vol
        hostPath:
          path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      nodePort: 30059
  type: NodePort

